server:
  port: 8090

debug: true

logging:
  level:
    com: debug

# Hibernate ddl auto (create, create-drop, validate, update)
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    #optimization for batching to group statements and send it in one
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma
    username: auth
    password: auth
  http:
    log-request-details: true
  liquibase:
    change-log: classpath:db/liquibase/db.changelog-master.yaml
  jackson:
    date-format: yyyy-MM-dd HH:mm

## App Properties
jwt:
  jwtSecret: JWTGeniousKey
  #4 hours
  jwtExpirationInMs: 14400000
application:
  stackTraceEnabled: false
date:
  pattern: yyyy-MM-dd HH:mm

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

kafka:
  server: localhost:9092
  application.id:
  diploma:
    number.partitions: 1
    replication.factor: 1
    consumer.group-id: dp
    max.poll.records: 50
    fetch.min.bytes: 1
    timeout: 200000
    defects:
      topic: diploma-defects
    streams:
      replication.factor: 1
      application.server.config: localhost:${server.port}
